### ISSUE TITLE
Explore using Model G and BB18 as PSV models

### ISSUE THREAD

**Issue by Swanson-Hysell** [PolarWandering/PaleoSampling#11]
In addition to doing runs using TK03, we can explore using Model G of McFadden and McElhinny (1988): https://doi.org/10.1029/JB093iB10p11583. This approach could be numerically more efficient given that VGP scatter which can be calculated using A and B coefficients and then linked to kappa.

**Comment by LenGallo** [comment]
The last function of this repo relates kappa (needed as input for the simulation) and latitude given two hardcoded values of A and B:

https://github.com/PolarWandering/PaleoStats/blob/main/dispersion_vs_concentration_vs_latitude.ipynb

It should be quite straightforward to implement, let me know if you need something else @facusapienza21 

To

**Comment by LenGallo** [comment]
Hi  @facusapienza21 @Swanson-Hysell,

I did some more modifications to the notebook. The final function is something like this, and you can find the rationale to get that in the notebook:

```
def kappa_from_latitude(latitude, a = 11.23, b=0.27, degrees = False):
    
    '''
    Input: given a latitude (in radians), and the $a$ and $b$ parameters that best describes the Model G that we want to simulate, 
    it returns the theoretical concentration parameter (kappa) that a sample of VGPs would have at any given latitude.
    Notes: 
     - we use a power-law fit to find an empirical relation between kappa and angular dispersion (found to be $ S = 72.33 \kappa^-0.50 $)
     - The default $a$ and $b$ values are from Doubrovine et al., (2019) (for the last 10 Ma - PSV10)
    '''    
    if degrees == False: latitude = np.degrees(np.abs(latitude_radians))
    
    S = np.sqrt(a**2+(latitude*b)**2) # approximate model G from Doubrovine et al. 2019     
    
    return 72.33 * np.power(S, -0.5)
```

**Comment by Swanson-Hysell** [comment]
Another paleosecular variation model that we can try using is BB18. The paper is here:
https://core.ac.uk/download/pdf/327988575.pdf

The code is here:
https://earthref.org/ERDA/2420/

The code is fast (although I need to engage with it to understand the outputs)

**Comment by facusapienza21** [comment]
We are currently sampling everything according to the G model, which is equivalent to Fisher with a kappa that depends on the site latitude.

**Comment by LenGallo** [comment]
Hi @facusapienza21 , @bramvaes , @duserzym , @Swanson-Hysell , @matdomeier ,  @Swanson-Hysell ,@duserzym , 

I just finished running Figure 1, but sampling from TK03 instead of Model G plus Fisher (there's a 256 cores cluster at the department and nobody uses it... so I don't care about execution time haha). I still have some work to do with the rest of the figures, but so far, I think that sampling from Fisher is just fine. Furthermore, I conducted some quick experiments and observed that for 50 VGPs randomly drawn from TK03 at 45 N, around 50% of them exhibit consistency with a fisher distribution (this relation decreases with increasing N). So, while I fully admit that TK03 is not 100% Fisherian at the vgp level, I think we are doing quite well.

![Figure1](https://github.com/PolarWandering/PaleoSampling/assets/29756069/8ff0b074-08ae-4f27-9010-cccccbbbe05b)
